### ISSUE TITLE
Add emis_order

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/vein#100]
Oi @Schuch666 . Eu vi que tu crio uma função nas rodadas do Bio-fuel para ordenar os dados horas das emissões com outras periodos. Eu acheio muito legal. Tu podería incluir uma função assima aqui por favor?

Ai tu muda o DESCRIPTION e te adiciona ai como "ctb", ou eu te adicono mais tarde.

Eu vou mudar a função depois para incluir diferentes tipos de objetos e  clases,

Obrigado

**Comment by Schuch666** [comment]
que bom que gostou da função, vou tentar adicionar aqui essa função acho que aqui no meu PC eu tenho como dar pull/push no vein, já fiz um esqueleto p testar com a inventory() quero fazer ela pegar de uma data o dia da semana

**Comment by ibarraespinosa** [comment]
deixa ela para usar matrices o data.frames, depois eu vejo as classes

**Comment by ibarraespinosa** [comment]
Mas se quiser mais real, segue o exemplo de emis_grid
