### ISSUE TITLE
avarege age  = NA message

### ISSUE THREAD

**Issue by Schuch666** [atmoschem/vein#131]
The following message on `age_ldv()`, `age_hgv()`' and `age_moto()` appears on the inventory default scrips:

Average age of PC is NA
Number of PC is 3.78 * 10^3 veh

If It's an problem, is better to display a warning/error for the user understood there is an error. if it's not a problem, can be added `rm.na = 'TRUE'` to display the this information.

**Comment by Schuch666** [comment]
This happen with an old São Lourenço do Sul net from OSM data

net <- readRDS('net.rds')
PC_01 <- age_ldv(x = net$ldv, name = 'PC', k = 3/4)

[net.zip](https://github.com/atmoschem/vein/files/2631368/net.zip)

**Comment by ibarraespinosa** [comment]
I see!
