### ISSUE TITLE
data("fkm")

### ISSUE THREAD

**Issue by Joaobazzo** [atmoschem/vein#137]
Hi Sergio,
The equation from `data("fkm"),` specifically `fkm$KM_LDV_GNV`, does not seem to be correct, comparing to  (BRUNI;BALES, 2013) study.

It reads,
`> body(fkm$KM_LDV_GNV)
{
    ifelse(age <= 20, 37958 * age - 0.291, 7958 * 20 - 0.291)
}`
but instead it should be 
`KM_LDV_GNV <- function(age){
  ifelse(age <= 20, 37958 * age^{- 0.291}, 37958 * 20^{- 0.291})
}`

According to (BRUNI;BALES, 2013)  https://cetesb.sp.gov.br/veicular/wp-content/uploads/sites/6/2013/12/curvas-intensidade-uso-veiculos-automotores-cidade-sao-paulo.pdf

**Comment by ibarraespinosa** [comment]
You are right! Thank you for that!
