### ISSUE TITLE
Error in EmissionFactorsList(x) : object 'efx' not found

### ISSUE THREAD

**Issue by vsbrand** [atmoschem/vein#186]
Estou tentando rodar o exemplo do vein, depois de eu rodar o inventory o programa dá problema no BUS_01_input.R no comando:
lefe <- EmissionFactorsList(x)
e dá o erro.

[1] "est/BUS_01_input.R"
[1] "CO"
Error in EmissionFactorsList(x) : object 'efx' not found

**Comment by ibarraespinosa** [comment]
Vou dar uma revisada nele. Obrigado.

**Comment by ibarraespinosa** [comment]
Agora funciona

```
library(vein)
name = file.path(tempdir(), "YourCity")
inventory(name = name, show.dir = TRUE, show.scripts = TRUE)
source(paste0(name, "/main.R"))

```
