### ISSUE TITLE
Processing time

### ISSUE THREAD

**Issue by Joaobazzo** [atmoschem/vein#189]
Hi Sérgio,

I'm having few troubles with the processing time of VEIN, mainly due to the big size of my data inputs. I'm wondering what approach you used to speed up the processing time in your simulations.

**Here's the input data**

    > # vehicle data distribution age
    > dim(veh1)
    [1] 79680    40
    > object.size(veh1)/10^6 # MB
    25.5 bytes

    > # profile of flow in 24 hours
    > dim(pc1)
    [1] 79680    24
    > object.size(pc1)/10^6 # MB
    20.4 bytes

    > # speed of the 24 hours
    > dim(speed1)
    [1] 79680    24
    > object.size(speed1)/10^6 # MB
    15.3 bytes

    > # net with 79680 elements
    > dim(net1)
    [1] 79680     4
    > object.size(net1)/10^6 # MB
    172.1 bytes

**Processing (error)** 

    >         # emissao CO
    >         system.time({
    +         E_pol <- emis(veh = veh1,lkm = net1$lkm, 
    +                       ef = LEF_v, speed = speed1,
    +                       profile = pc1)
    +         })
     Error: cannot allocate vector of size 24.3 Mb Timing stopped at: 71.39 38 231.7

**Alternative**

I tried to break down the data inputs, say reducing it to the first `1000` lines, but it still takes around 8 minutes - which means it would take around 11 hours (only for one type of fuel and engine size)

    >         # emissao CO
    >         system.time({
    +         E_pol <- emis(veh = veh1[1:1000,],lkm = net1$lkm[1:1000], 
    +                       ef = LEF_v, speed = speed1[1:1000,],
    +                       profile = pc1[1:1000,])
    +         })
       user  system elapsed 
     414.53   36.53  473.77 

Do you have any ideas?

**Comment by ibarraespinosa** [comment]
Well, this is strange, because I use to work with up to 70,000 streets per run. Could you provide tour sessionInfo()? Also, send me some of your data to take a closer look.

**Comment by Joaobazzo** [comment]
I'll organize my data to send you a dropbox link, in the meantime

    > sessionInfo()
    R version 3.6.0 (2019-04-26)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 17134)

    Matrix products: default

    Random number generation:
     RNG:     Mersenne-Twister 
     Normal:  Inversion 
     Sample:  Rounding 
 
    locale:
    [1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252   
    [3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
    [5] LC_TIME=Portuguese_Brazil.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] vein_0.7.12

    loaded via a namespace (and not attached):
     [1] Rcpp_1.0.1         lattice_0.20-38    codetools_0.2-16   class_7.3-15      
     [5] sf_0.7-7           grid_3.6.0         DBI_1.0.0          magrittr_1.5      
     [9] units_0.6-3        e1071_1.7-2        KernSmooth_2.23-15 ncdf4_1.16.1      
    [13] data.table_1.12.2  raster_2.9-5       sp_1.3-1           tools_3.6.0       
    [17] compiler_3.6.0     classInt_0.3-3     eixport_0.3.6      cptcity_1.0.4

**Comment by ibarraespinosa** [comment]
Also, could you please use the function `vein_notes` and paste the output of the resulting .txt file here?

Thanks

**Comment by Joaobazzo** [comment]
I've never used `vein_notes` function and had a bit of trouble understanding it (but will take a look soon!) ...I used `dput()` function to display the first 10 lines of input data

[first_10lines.txt](https://github.com/atmoschem/vein/files/3517234/first_10lines.txt)

**Comment by ibarraespinosa** [comment]
Your emission factors are expressed with constant functions. If you want to use speed functions you better use ef_ldv_scale or ef_hdv_scale, please check:

?ef_ldv_scaled
?ef_hdv_scaled

However, your error seems related to the RAM capacity of your laptop.

ensure that when you are running VEIN, **DO NOT USE GOOGLE CHROME** (or use only one tab)

If you use vein_notes, you will see ho much RAM you are using.

You can also try to reduce the number of streets. Try aggregating some traffic flow in some streets, and avoid using residential streets for instance, if that is OK for your method.

**Comment by Joaobazzo** [comment]
I used constant functions for emission factor because of the fuel (ethanol), that does not have speed dependent functions. However, for gasoline, I do use `ef_ldv_scaled`. Is it correct, right?

Thanks for the `vein_notes` function tips, I'll take a look at it!

**Comment by ibarraespinosa** [comment]
If you assume that flex etanol and etanol vehicules have a speed variation
similar to gasoline, it think it would still be valid.
However, I would suggest this, in the following order if possible
Measure emissions of vehicules usign ethanol with PEMS or different driving
cycles to create speed functions
if it is not possible, find some speed functions from literature for this
type of vehicles
If it not possible, use ef_ldv_scaled to create speed functions for your
ethanol vehicles. Remember that ef_ldv_scaled and ef_hdv_scaled just
incorporate speed variation  to your local emission factor. Which means, if
your local emission factor was measure with a driving cycle with  a certain
average speed, the resulting speed function will return exactly the same
value of your local emission factor for the same speed.


[image: photo]
*Sergio Ibarra Espinosa*
Postdoc, PhD. in Atmospheric Sciences, MSc Environment, Engineer, Universidade
de São Paulo & Chinese Academy of Sciences

+ 8617643016295 <++8617643016295> | +55 11 974 253 791 <+55+11+974+253+791>
| sergio.ibarra@usp.br

www.sergioibarra.blogspot.com | Skype: sergio_ibarra1
<#SignatureSanitizer_SafeHtmlFilter_>
Rua do Matão, 1226 - Cidade Universitária São Paulo-SP - Brasil - 05508-090
<http://github.com/ibarraespinosa> <http://us.linkedin.com/in/sibarra>
<http://wiseintro.co/sergioibarra> <http://blogger.com/profile/sergioibarra>
Get your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>


Em seg, 19 de ago de 2019 às 21:06, João Bazzo <notifications@github.com>
escreveu:

**Comment by Joaobazzo** [comment]
Actually, the problem seemed to be with the profile data input, I was using the wrong format,

    > # profile of flow in 24 hours
    > dim(pc1)
    [1] 79680    24
    > object.size(pc1)/10^6 # MB
    20.4 bytes

It was supposed to be only a normalization for 24 hours, with dimensions of `[1 24]` and not `[79680 24]`. In my case of study, the daily traffic flow has the same behaviour. Thank you!

**Comment by ibarraespinosa** [comment]
I see

Please, check

data(profiles)

Or

data(pc_profile)

One dimension is number of days and the other is 24 hours. If you have a
matrix 24x7 your flow will be expanded to 168 hours (24x7)

I'm closing this
