### ISSUE TITLE
install Error

### ISSUE THREAD

**Issue by Schuch666** [atmoschem/vein#192]
I got this odd error installing on a remote machine, do you have any suggestion to fix this?

```{r}> remotes::install_github('atmoschem/vein')
Downloading GitHub repo atmoschem/vein@master
Running R CMD build...
* checking for file '/tmp/RtmpSi9kGA/remotes1b2b1c2b57b/atmoschem-vein-cc49817/DESCRIPTION' ... OK
* preparing 'vein':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'vein_0.8.0.tar.gz'
* installing *source* package 'vein' ...
** using staged installation
** R
Error in load(srcFile, e) : 
  (converted from warning) strings not representable in native encoding will be translated to UTF-8
ERROR: unable to build sysdata DB for package 'vein'
* removing '/global/u1/s/schuch/R-3.6.1/library/vein'
Error: Failed to install 'vein' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpSi9kGA/file1b2b346728eb/vein_0.8.0.tar.gz' had non-zero exit status ```

**Comment by ibarraespinosa** [comment]
install from CRAN and try again. it is the same version

**Comment by ibarraespinosa** [comment]
Funciounou @Schuch666 ?

**Comment by Schuch666** [comment]
Parcialmente

A versão do CRAN instala, porém dá uns erros quando rodando a função inventory(), por exemplo, ele cria a estrutura mas não cheguei a testar se faltou alguma coisa.

O erro está relacionado a dependência de programas no PATH que usam versões diferentes de bibliotecas das que estão no meu ambiente. Tem uma chamada do editor **vi** (que requer versões diferentes das bibliotecas de compactação) no teste que fiz, o vein usa o **vi**?

**Comment by ibarraespinosa** [comment]
inventory abre o editor por default do OS, a funçlao usa file.edit mas vou mudar ela para file.open ou algo assim. Como o problema não e sobre a isntalação mas sobre o editor que depende de cada OS vou fechar este issue, mas vou abrir outro sobre o problema mencionado. Obrigado
