### ISSUE TITLE
problems when file.edit in inventory (SUSE Linux Enterprise Server 15)

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/vein#193]
inventory abre por default um arquivo que depende do editor de texto de cada OS. @Schuch666  tu poderia adicionar mais informação do problema incluindo sessionInfo por favor? 

Obrigado

**Comment by Schuch666** [comment]
claro:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: SUSE Linux Enterprise Server 15

Matrix products: default
BLAS:   /global/u1/s/schuch/R-3.6.1/lib/libRblas.so
LAPACK: /global/u1/s/schuch/R-3.6.1/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] vein_0.8.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         lattice_0.20-38    codetools_0.2-16   class_7.3-15
 [5] sf_0.8-0           grid_3.6.1         DBI_1.0.0          magrittr_1.5
 [9] units_0.6-4        e1071_1.7-2        ncdf4_1.16.1       KernSmooth_2.23-15
[13] data.table_1.12.2  raster_3.0-7       sp_1.3-1           tools_3.6.1
[17] compiler_3.6.1     classInt_0.4-1     eixport_0.3.6      cptcity_1.0.4
```
E o erro:
```
> vein::inventory('test')
files at test
Directories:
 [1] "test"              "test/ef"           "test/emi"
 [4] "test/emi/BUS_01"   "test/emi/HGV_01"   "test/emi/LCV_01"
 [7] "test/emi/MC_01"    "test/emi/PC_01"    "test/est"
[10] "test/images"       "test/network"      "test/post"
[13] "test/post/df"      "test/post/grids"   "test/post/streets"
[16] "test/profiles"     "test/veh"
vi: /global/homes/s/schuch/local_libs/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib64/libpng16.so.16)
```
Uma ideia seria checar se está usado o RStudio e abrir em uma aba do RStudio se for o caso (como a função use_test do devtools)

**Comment by ibarraespinosa** [comment]
se tu coloca

`inventory('test', show.main = FALSE) 
`
deveria rodar sem tentar abrir o main.R usando vi

**Comment by Schuch666** [comment]
Verdade, será que não é melhor usar essa opção como padrão?

**Comment by ibarraespinosa** [comment]
Se tu atualiza desde GitHub poderia ver que agora nao abre o main.R por default. Obrigado

**Comment by Schuch666** [comment]
instalando a versão do github dá esse erro:

``` 
* checking for file '/tmp/RtmpkE0aNn/remotesdce2732b90e9/atmoschem-vein-369bc76```
/DESCRIPTION' ... OK
* preparing 'vein':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'vein_0.8.1.tar.gz'
* installing *source* package 'vein' ...
** using staged installation
** R
Error in load(srcFile, e) :
  (converted from warning) strings not representable in native encoding will be translated to UTF-8
ERROR: unable to build sysdata DB for package 'vein'
* removing '/global/u1/s/schuch/R-3.6.1/library/vein'
* restoring previous '/global/u1/s/schuch/R-3.6.1/library/vein'
Error: Failed to install 'vein' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpkE0aNn/filedce26ae0e3dc/vein_0.8.1.tar.gz' had non-zero exit status
```

Aqui no meu PC instala com warning:
```
Warning in load(srcFile, e) :
  strings not representable in native encoding will be translated to UTF-8
```

depois de instalado:
```
> vein::inventory('test')
```
funciona bem

mas rodando:
```
vein::inventory('test',show.main = T)
```

dá abre um editor e quando fecha ele já dá source e retorna esse erro:

> 
> Reading emissions from:
> [1] "emi/BUS_01_CO_STREETS.rds" "emi/HGV_01_CO_STREETS.rds" "emi/LCV_01_CO_STREETS.rds"
> [4] "emi/MC_01_CO_STREETS.rds"  "emi/PC_01_CO_STREETS.rds" 
> Error in editor(file = file, title = title) : 
>   Error in sf::st_as_sf(g) : object 'g' not found
> You can attempt to correct the error using test/main.R = edit()
> In addition: Warning messages:
> 1: In if (class(spobj) == "bbox") { :
>   the condition has length > 1 and only the first element will be used
> 2: In emis_merge("CO", net = net) : NAs introduced by coercion
> Called from: editor(file = file, title = title)

**Comment by ibarraespinosa** [comment]
eu acho que é um warning da função make_grid. Agora mudei a função e não da mais esse warning. Aqui no Ubuntu não tenho erro, neste commig https://github.com/atmoschem/vein/commit/74e891e4d72b201d6292711ffcf4374297ff1199
DA uma olhada e me avisa por favor

**Comment by Schuch666** [comment]
Continua o mesmo warning (PC) e erro (server)

**Comment by ibarraespinosa** [comment]
entoa segue com a versao de CRAN

**Comment by ibarraespinosa** [comment]
me diz se a versão do CRAN funciona

**Comment by Schuch666** [comment]
Funciona, com `show.main = F` não dá erros na função `inventory()`
