### ISSUE TITLE
Example utilising dodgr package? 

### ISSUE THREAD

**Issue by airqualityanthony** [atmoschem/vein#199]
Is it possible to get a run through detailed example utilising the referenced pacakge 'dodgr' to generate traffic flows in the correct format for VEIN?

This would really help aid development of custom examples in user selected locations, without huge knowledge of transport models? 

Ideally being able to select a location using the example code found in the dodgr documentation;

```
## bounding box around york
bb <- osmdata::getbb ("york uk")
npts <- 1000
xy <- apply (bb, 1, function (i) min (i) + runif (npts) * diff (i))
bb; head (xy)

## get osm data for bb
net <- dodgr_streetnet (bb)

```

**Comment by ibarraespinosa** [comment]
Hello, I will check and let you know ASAP

**Comment by ibarraespinosa** [comment]
@airqualityanthony I did it like two years ago and I dont have back ups for the scripts. I recommend you to read the documentation of https://github.com/ATFutures/dodgr, developed by @Robinlovelace and @mpadge. Anyways, I remember that you would an origin-destination matrix.

Anyways,  I followed installed the GitHub version of dodgr and ran the vignette https://atfutures.github.io/dodgr/articles/flows.html. My recommendation is to read the documentation of dodgr.

library(dodgr)
bb <- osmdata::getbb ("york uk")
npts <- 1000
xy <- apply (bb, 1, function (i) min (i) + runif (npts) * diff (i))
bb; head (xy)

## get osm data for bb
graph <- dodgr_streetnet(bb)
graph <- weight_streetnet (graph, wt_profile = "psv")
from <- sample (graph$from_id, size = 10)
to <- sample (graph$to_id, size = 10)
flows <- matrix (10 * runif (length (from) * length (to)),
                 nrow = length (from))

graph_f <- dodgr_flows_aggregate (graph, from = from, to = to, flows = flows)
head (graph_f)

summary (graph_f$flow)

graph_undir <- merge_directed_graph (graph_f)
graph <- graph [graph_undir$edge_id, ]
graph$flow <- graph_undir$flow
graph_f <- graph_f [graph_f$flow > 0, ]
dodgr_flowmap (graph_f, linescale = 5)

Another alternative would check https://movement.uber.com/ to download speeds and use a speed/traffic flow approach. You could also, have access to RADAR data and produce traffic flows, or use cameras with OCR or OpenCV.

![image](https://user-images.githubusercontent.com/27447280/73963648-7c6b1e80-48ef-11ea-881e-ead74fc5a307.png)

**Comment by ibarraespinosa** [comment]
I'm closing this. Once you have traffic flow let me know @airqualityanthony
