### ISSUE TITLE
Update HDV emission factor from EMEP/EEA?

### ISSUE THREAD

**Issue by Joaobazzo** [atmoschem/vein#205]
Hi Sérgio, I've been doing some research to check `fuel consumption` data and consequently `CO2`
I've found three links from EMEP/EEA that has `fuel consumption` data for buses
These links are:

[EMEP 2007](https://www.eea.europa.eu/publications/EMEPCORINAIR5/HDV_functions_Excel_files.zip/view)
[EMEP 2009](https://www.eea.europa.eu/publications/emep-eea-emission-inventory-guidebook-2009/part-b-sectoral-guidance-chapters/1-energy/1-a-combustion/1.a.3.b-road-transport-annex-hdv-files.zip/view)
[EMEP 2013](https://www.eea.europa.eu/publications/emep-eea-guidebook-2013/part-b-sectoral-guidance-chapters/1-energy/1-a-combustion/1-a-3-b-road-transport-annex-hdv-files.zip/view)
From EMEP 2013, we don't have data anymore for `FC`, neighter in [EMEP 2016](https://www.eea.europa.eu/publications/emep-eea-guidebook-2016/part-b-sectoral-guidance-chapters/1-energy/1-a-combustion/1-a-3-b-i-1/view) nor [EMEP 2019](https://www.eea.europa.eu/publications/emep-eea-guidebook-2019/part-b-sectoral-guidance-chapters/1-energy/1-a-combustion/road-transport-appendix-4-emission/view)

From what I've checked, your `sysdata$hdv_criteria` is using data from EMEP2007. Here is some quick reproducible example.
```r
    library(openxlsx)
    library(readxl)
    library(magrittr)
    library(data.table)

    link_vein <- "https://github.com/atmoschem/vein/blob/master/R/sysdata.rda?raw=true"
    download.file(url = link_vein,destfile = "sysdata.rda")
    load("sysdata.rda")
    hdv <- data.table::setDT(sysdata$hdv_criteria)[VEH %in% "Ubus" & 
                                                     TYPE %in% "Std" & 
                                                     EURO %in% "V" &
                                                     GRA == 0.0  & 
                                                     LOAD == 0.5 & 
                                                     POLLUTANT %in% "FC",]
    # 2007 data
    link2007 <- "https://www.eea.europa.eu/publications/EMEPCORINAIR5/HDV_functions_Excel_files.zip/at_download/file"
    a <- tempdir()
    zipfile2007 <- paste0(a,"/HDV_functions_Excel_files.zip")
    download.file(url = link2007,destfile = zipfile2007)
    unzip(zipfile = zipfile2007, exdir = a)
    # list.files
    # list.files(a)
    # read file with LOAD 50% and Gradient 0%
    filepath2007 <- paste0(a,"/EFs_G00%_L050%.xls")
    emep2007 <- readxl::read_xls(path = filepath2007,sheet = "FC") %>% data.table::setDT()
    #> New names:
    #> * `` -> ...6
    #> * `` -> ...8
    #> * `` -> ...14
    emep2007 <- emep2007[Subsegment %in% "Ubus Std >15-18t Euro-5",]
    emep2007
    #>    ID Subsegment              Subsegment Gradient (%) Load (%) Pollutant ...6
    #> 1:        727250 Ubus Std >15-18t Euro-5            0      0.5        FC   NA
    #>                         Formula (y: g/km; x: km/h) ...8        a          b
    #> 1: y=((e+(a*exp(((-1)*b)*x)))+(c*exp(((-1)*d)*x)))   NA 631.2044 0.06775371
    #>          c        d        e ...14        r2 Chi sq'd Norm. Chi Min x (km/h)
    #> 1: 5907007 1.841799 185.9967    NA 0.9771904 25133.04  16.26525            6
    #>    Max x (km/h)
    #> 1:           75

    # you can see that parameters are the same as sysdata$hdv_criteria
    hdv
    #>        id              Subsegment  VEH TYPE         GW EURO GRA LOAD POLLUTANT
    #> 1: 727250 Ubus Std >15-18t Euro-5 Ubus  Std >15 & <=18    V   0  0.5        FC
    #>                                                Y       a       b       c      d
    #> 1: ((e+(a*exp(((-1)*b)*V)))+(c*exp(((-1)*d)*V))) 631.204 0.06775 5907007 1.8418
    #>          e        r2   Chisqr  Normchi MINV MAXV  typepol X X.1 X.2
    #> 1: 185.997 0.9771904 25133.04 16.26525    6   75 criteria    NA  NA

    # my suggestion is to work with 2016's data
    link2016 <- "https://www.eea.europa.eu/publications/emep-eea-guidebook-2013/part-b-sectoral-guidance-chapters/1-energy/1-a-combustion/1-a-3-b-road-transport-annex-hdv-files.zip/at_download/file"
    a <- tempdir()
    zipfile2016 <- paste0(a,"/1.A.3.b.i-iv Exhaust emissions from road transport annex HDV files.zip")
    download.file(url = link2016,destfile = zipfile2016)
    unzip(zipfile = zipfile2016, exdir = a)
    # list files
    # list.files(a)
    filepath2016 <- paste0(a,"/1.A.3.b.i-iv Exhaust emissions from road transport data annex Sept2014 update.xlsx")

    openxlsx::getSheetNames(filepath2016)
    #> [1] "PCs - LDVs Equations" "PCs"                  "LDVs"                
    #> [4] "HDV - BUS Equations"  "HDVs - BUS"
    emep2016 <- openxlsx::read.xlsx(xlsxFile = filepath2016,sheet = "HDVs - BUS") %>% 
      data.table::setDT()
    mydata2016 <- emep2016[Sector %in% "Buses" & 
                             `Sub-Sector` %in% "Urban Buses Standard 15 - 18 t" & 
                             Pollutant %in% "FC" & 
                             Slope == 0.0  & 
                             Load == 50 & 
                             Technology %like% "Euro V ",]
    #
    # here you can see that the values changes a little lit, also the equations
    #
    mydata2016
    #>    Sector                     Sub-Sector      Technology Euro.No. Load Slope
    #> 1:  Buses Urban Buses Standard 15 - 18 t HD Euro V - EGR        5   50     0
    #> 2:  Buses Urban Buses Standard 15 - 18 t HD Euro V - SCR        5   50     0
    #>    Pollutant      Alpha        Beta       Gamma Delta Epsilon Zita Ita Thita RF
    #> 1:        FC 184.115566 -0.78290609  0.02963099     0       0    0   0     0  0
    #> 2:        FC   6.994623 -0.08009671 -0.41313169     0       0    0   0     0  0
    #>           R2    Equation
    #> 1: 0.9467285 Equation 12
    #> 2: 0.9547610 Equation 16
    #>                                                       Formula Vmin Vmax
    #> 1: y = ((Alpha / (1 + (Beta * Exp(((-1) * Gamma) * Speed)))))   11   86
    #> 2: y = (Exp((Alpha + (Beta / Speed)) + (Gamma * Log(Speed))))   11   86
    #>          EF 50
    #> 1: 223.9693 50
    #> 2: 539.7589 50
```
<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If you think it looks correct, I'll update `gtfs2emis` with 2016 data doing some web scraping and then `sysdata.rds` in vein could be updated as well.

**Comment by Joaobazzo** [comment]
Actually, EMEP2016 EF data.base has only emission factors for Euro V and VI =(, so I'll take a look at some other sources, such as EMEP2009 and EMEP2007, to complement this data.

**Comment by ibarraespinosa** [comment]
That is a great use of reprex.

Man, I need help with that. Pull requests are more than welcome. To my experience, the best way to update the software, is to using it. As I have been developing vehicular emissions for Brazil, those emission factors have been updated (actually, I need to a new VOC speciation for Brazil). As you are working on gtfs2emis you can see that. I will think about some application for Europe so that we can make full upgrade of European EF in VEIN. How about that?

**Comment by Joaobazzo** [comment]
Yes, Sérgio, since I've been building a script to prepare Europen EF, so I can submit a Pull Request to VEIN. I think it would be easy to have a folder in VEIN repository with preparation scripts, similar to the one we have in [gtfs2emis](https://github.com/rafapereirabr/gtfs2emis/tree/master/data-raw). So I can submit a Pull Request and you can check and run on your machine as well.

**Comment by ibarraespinosa** [comment]
Man that would be awesome.

I`m just concerned about the format that these data.frame are read into
ef_ldv_speed. ef_ldv_speed and ef_hdv_speed, at the moment, requires the
data.frames with the right colnames so that the functions worked as
usual.If you generate the hdv_criteria I could generate the other data sets
(GHG, species PM and so on). As you can image, these data-sets are actually
firstly generated in Excel and then I prepare R to read them. Therefore,
the future steps for ef_*_speed functions are:


   - transform to data.tables instead of data.frames
   - include a smarter way of speciation. This could be with relational
   data.frames.




Em qua., 30 de set. de 2020 às 09:01, João Bazzo <notifications@github.com>
escreveu:

**Comment by Joaobazzo** [comment]
ok, I'll take a look at the code I created for [gtfs2emis](https://github.com/rafapereirabr/gtfs2emis/blob/master/data-raw/europe.R) and adjust a little bit for VEIN
