### ISSUE TITLE
Installation error for macOS, update by github/gitlab

### ISSUE THREAD

**Issue by YingW1014** [atmoschem/vein#215]
I am a Mac user who is using VEIN v0.9.1.2. I want to update it to 0.9.1.3, which is not available by CRAN. I met an installation error when updating VEIN by github/gitlab. The error code is as follows:

gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  e_bottomup.f95 -o e_bottomup.o
make: gfortran: No such file or directory
make: *** [e_bottomup.o] Error 1
ERROR: compilation failed for package ‘vein’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/vein’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/vein’
Error: Failed to install 'vein' from GitHub:
  (converted from warning) installation of package ‘/var/folders/y5/6m884ggd3rl3gt2nzxxc8zmr0000gp/T//Rtmp3ZFxDk/file726477a0c90/vein_0.9.1.3.tar.gz’ had non-zero exit status

**Comment by ibarraespinosa** [comment]
Hello Ying, 

It seems that you do not have gfortran on your system. Follow this [link](https://stackoverflow.com/questions/47472715/cannot-install-fortran-program-on-macos-via-terminal) and then try installing VEIN again.

*however*, the lasts updates on VEIN have been made for Brazilian emission factors. Then,  i think using VEIN 0.9.1.2 might be just fine.
