### ISSUE TITLE
sf 1.0-1 is going to break vein (again...)

### ISSUE THREAD

**Issue by edzer** [atmoschem/vein#216]
https://github.com/atmoschem/vein/commit/f5f35785469882bda54e9d75df9a10ee3d3c5086 needs to be reverted: this was caused by a _regression_ in sf, which will be corrected in sf 1.0-1, see https://github.com/r-spatial/sf/issues/1704 ; replacing 5638228 with the original (correct) 1946955 (in both places) should do the job. Sorry for the trouble!

(see also here: https://win-builder.r-project.org/incoming_pretest/sf_1.0-1_20210627_093444/reverseDependencies/summary.txt)

**Comment by ibarraespinosa** [comment]
thanks for the update @edzer
