### ISSUE TITLE
remove  dependencies

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/vein#227]
By the end of this year VEIN 1.0.0 will be submitted to CRAN, 

One publication is expected

VEIN needs to be cleaned and some helper functions will be deprecated, today they show a message

fields is used only by the image.plot, but I need to generate a new function base-based to plot classes

**Comment by ibarraespinosa** [comment]
Currently, vein imports fields, which is not necessary.
https://github.com/atmoschem/vein/blob/0349c34da1a496d6b2c9b20bea697002d9942ec9/DESCRIPTION#L27

I need to change to modified  filled.contour

**Comment by Schuch666** [comment]
Fields removed in cfdff0bfc9db4a4a514a6fbdce163dc6a5c00ffc
