### ISSUE TITLE
Issues with the upcoming release of units 0.8-2

### ISSUE THREAD

**Issue by Enchufa2** [atmoschem/vein#253]
Dear maintainer,

We are preparing units 0.8-2 for release. I'm writing to you because our revdep checks report new issues in your package with this new version (you can check them [here](https://github.com/r-quantities/units/blob/main/revdep/problems.md#vein)).

The issue is raised in [this test](https://github.com/atmoschem/vein/blob/d2a5c33ba62babe1384db0a6d696199bd9c15f4c/tests/testthat/test-ef_china.R#L384-L388), and it's caused by the fact that this function accesses the internals of the unit [here](https://github.com/atmoschem/vein/blob/d2a5c33ba62babe1384db0a6d696199bd9c15f4c/R/ef_china.R#L193-L198).

The internals are subject to change, so this should be avoided. If you want to compare units exactly, please rely on their methods:

``` r
library(units)
#> udunits database from /usr/share/udunits/udunits2.xml

x <- set_units(3, km/h)
units(x) == units(as_units("km/h"))
#> [1] TRUE
```

or, in a more general way, you can check if units are compatible:

``` r
x <- set_units(3, m/s)
ud_are_convertible(x, as_units("km/h"))
#> [1] TRUE
```

**Comment by ibarraespinosa** [comment]
Hola @Enchufa2 , gracias por el mensaje. Cambiare el  codigo. Saludos!
