### ISSUE TITLE
fix cb05

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/vein#257]
According to a successful CB05 run with WRF Chem, CB05 must have the following groups. 
However, the list has C2H5OH and ETOH. 
I need to confirm this, @Schuch666 , can you please confirm if a CB05 run need both groups?

|group        |  VEIN
|---------------|------------|
| ALD2       |CB05opt2|
| ALDX     |CB05opt2|
| BENZENE  |CB05opt2|
| CH4  |emitted|
| CL2  ||
| CO  |emitted|
| ECC  | speciated?|
| ECI  |speciated as pm|
| ECJ  |speciated as pm|
| ETH  |CB05opt2|
| ETHA  |CB05opt2|
| ETOH  | emitted as ETOH|
| FORM  |CB05opt2|
| HCL  ||
| HONO  ||
| IOLE  |CB05opt2|
| ISOP  ||
| MEOH  ||
| NH3  | emitted|
| NH4I  | speciated as pm|
| NH4J  |speciated as pm|
| NO  |emitted|
| NO2  |emitted|
| NO3C  |speciated as pm|
| NO3I  |speciated as pm|
| NO3J  |speciated as pm|
| OLE  |CB05opt2|
| ORGC  |speciated as pm|
| ORGI  |speciated as pm|
| ORGJ  |speciated as pm|
| PAR  |CB05opt2|
| PM10  |emitted|
| PM25  |emitted|
| PM25I  |speciated as pm|
| PM25J  |speciated as pm|
| PSULF  |
| SO2  |emitted|
| SO4C  |speciated as pm|
| SO4I  |speciated as pm|
| SO4J  |speciated as pm|
| TERP  |
| TOL  |CB05opt2|
| XYL  |CB05opt2 |

**Comment by Schuch666** [comment]
Hi Sergio,

What do you mean by a successful CB05 run with WRF Chem? 

The model will try to use the species defined in the registry depending on the emiss_opt option (other variables inside the emission file are not used). Each chemical mechanism in WRF-Chem, for CB05 the recommended emiss_opt is ecb05_opt1 (15) and emiss_inpt_opt = 101. The list of the species are in the registry and a copy on eixport try data('emiss_opt').
The species for this option are:
library(eixport)
data('emiss_opt')
emis_opt$ecb05_opt1
 [1] "E_NO2"    "E_XYL"    "E_TOL"    "E_TERP"   "E_SO2"    "E_ORA2"   "E_OLT"    "E_OLI"    "E_OL2"    "E_NO"    
[11] "E_NH3"    "E_ISO"    "E_HCL"    "E_HCHO"   "E_ETH"    "E_CSL"    "E_CO"     "E_CH3OH"  "E_C2H5OH" "E_ALD"   
[21] "E_ALDX"   "E_HC3"    "E_HC5"    "E_HC8"    "E_KET"    "E_PM25I"  "E_PM25J"  "E_ECI"    "E_ECJ"    "E_ORGI"  
[31] "E_ORGJ"   "E_SO4I"   "E_SO4J"   "E_NO3I"   "E_NO3J"   "E_SO4C"   "E_NO3C"   "E_ORGC"   "E_ECC"    "E_PM10"

I think you only need "E_C2H5OH" (and "E_ETOH" is not used by WRF_Chem) if I understood correctly the question

**Comment by ibarraespinosa** [comment]
I'm confused, I'm updating a table and I will write it here

**Comment by ibarraespinosa** [comment]
I make a comparison and both, CB05 and CB05opt2 from VEIN are compatible with emis_opt from registry.chem. Then, I do not know why I have not been able to run CB05

| ecb05_opt1 | VEIN-CB05 | ecb05_opt2 | VEIN-CB05op2 | CB05 someone |
|------------|-----------|------------|--------------|--------------|
| E_ALD      | ALD       |            |              |              |
|            |           | E_ACET     |              |              |
|            |           | E_ALD2     | E_ALD2       | E_ALD2       |
| E_ALDX     | ALDX      | E_ALDX     | E_ALDX       | E_ALDX       |
| E_HC3      | HC3       | E_ALK3     |              |              |
| E_HC5      | HC5       | E_ALK4     |              |              |
| E_HC8      | HC8       | E_ALK5     |              |              |
|            |           | E_BALD     |              |              |
|            |           |            | E_BENZENE    | E_BENZENE    |
|            |           | E_CCOOH    |              |              |
| E_C2H5OH   | C2H5OH    |            |              |              |
| E_CH3OH    | CH3OH     |            |              |              |
|            |           |            | E_CH4        | E_CH4        |
|            |           |            |              | E_CL2        |
|            |           | E_CRES     |              |              |
| E_CSL      | CSL       |            |              |              |
| E_ETH      | ETH       | E_ETH      | E_ETH        | E_ETH        |
|            |           | E_ETHA     | E_ETHA       | E_ETHA       |
|            |           | E_ETOH     | E_ETOH       | E_ETOH       |
|            |           | E_FORM     | E_FORM       | E_FORM       |
|            |           | E_GLY      |              |              |
| E_HCL      |           | E_HCL      | E_HCL        | E_HCL        |
| E_HCHO     | E_HCHO    |            |              |              |
|            |           |            |              | E_HONO       |
|            |           | E_HCOOH    |              |              |
|            |           | E_IOLE     | E_IOLE       | E_IOLE       |
|            |           | E_IPROD    |              |              |
| E_ISO      | ISO       | E_ISOP     | E_ISOP       | E_ISOP       |
| E_KET      | KET       |            |              |              |
|            |           | E_MACR     |              |              |
|            |           | E_MEK      |              |              |
|            |           | E_MEO2     |              |              |
|            |           | E_MEOH     | E_MEOH       |              |
|            |           | E_MGLY     |              |              |
| E_OLI      | OLI       |            |              |              |
| E_OL2      | OL2       |            |              |              |
| E_OLT      | OLT       |            |              |              |
|            |           | E_OLE      | E_OLE        | E_OLE        |
| E_ORA2     | ORA2      |            |              |              |
|            |           | E_PAR      | E_PAR        | E_PAR        |
|            |           | E_PHEN     |              |              |
| E_TERP     | TERP      | E_TERP     | E_TERP       | E_TERP       |
| E_TOL      | TOL       | E_TOL      | E_TOL        | E_TOL        |
| E_XYL      | XYL       | E_XYL      | E_XYL        | E_XYL        |

**Comment by ibarraespinosa** [comment]
I checked and CB00opt2 with I am using **chem_opt as 132** and should be enough. I will try again running WRF Chem
 **emiss_inpt_opt                      = 101**

**Comment by Schuch666** [comment]
Hi @ibarraespinosa , sorry for my late reply

Yeah, it is very hard to ping pong the exact cause here.
I don`t see anything wrong that can cause an error in your approach (but maybe some emission are double counted, but that`s will affect your results), but the WRF-Chem using this options is less stable and sometimes even the meteorology options can present some problem.

Were are you running the simulation? do you have access to Stamede2 or Cheyenne?

**Comment by ibarraespinosa** [comment]
nope. I was thinking for Brazilian runs. U have access to cheyenne, but to
run MUSICA
