### ISSUE TITLE
name of emisson variables

### ISSUE THREAD

**Issue by Schuch666** [atmoschem/vein#71]
change the names of the grindedemissionarrays (or the emis_grid output) for a more explanatory (and useful for plots) name. A idea is to use the sprintf() function like:

last_hour <- 168
paste0("hour_",sprintf('%0.3d', 0:last_hour)) or paste0("hour_",sprintf('%0.4d', 0:last_hour))

remember to change in the plot inside inventory

**Comment by Schuch666** [comment]
PS: I tried to change this in GriddedEmissionsArray.R but nothing change

**Comment by ibarraespinosa** [comment]
Well spotted, I agree. The length of the names vector will vary according to the length of the hours of the emissions. I believe It would be very simple to change it.
