### ISSUE TITLE
add read_gtfs

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/vein#96]
Need it

**Comment by Joaobazzo** [comment]
I know the `stplanr` package has a function called `gtfs2sldf ` to import GTFS shapes and route data to SpatialLinesDataFrame. Perhaps its worth to take a look

**Comment by ibarraespinosa** [comment]
Totalmente

**Comment by ibarraespinosa** [comment]
https://github.com/ipeaGIT/gtfs2gps already to this nicely
